---

- name: install nginx
  yum:
    name: nginx
    state: present
  notify: 
    - start postgresql
  when:
    - ansible_distribution == "CentOS"

- name: make sure filefolder exists
  file: path="{{item}}" state=directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: install nginx conf
  template: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - {'src': 'nginx.conf' , 'dest':'/etc/nginx/nginx.conf'}

- name: install myapp template
  template: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - {'src': 'myapp.conf' , 'dest':'/etc/nginx/sites-available/myapp.conf'}