---

- name: configure apache httpd.conf 
  lineinfile: 
    dest: "{{user_root}}/apache/conf/httpd.conf"
    regexp: "{{item.regexp}}" 
    insertafter: "{{item.insertafter}}"
    line: "{{item.line}}"
  with_items:
    - {regexp: "^Listen ", insertafter: "^#Listen ", line: "Listen {{httpd_port}}"}
    - {regexp: "^User ", insertafter: "^#User ",line: "User {{ user }}"}
    - {regexp: "^Group ", insertafter: "^#Group ",line: "Group {{ group }}"}
    - {regexp: "^ServerName ", insertafter: "^#ServerName ",line: "ServerName {{server_name}}"}

      

- name: Load config files from the config directory conf.d/*.conf
  lineinfile:
    dest: "{{user_root}}/apache/conf/httpd.conf"
    line: "{{item.line}}"
  with_items:
    - {line: "Include conf.d/*.conf"}


- name: make sure path must exists
  file: path="{{user_root}}/apache/conf.d/" state=directory
    

#- name: use template to upload configure
#  template: src="{{item.src}}" dest="{{item.dest}}" owner={{ user }} group={{ group }}
#  with_items:
#    - {'src': 'green-web.conf.j2', 'dest':'{{user_root}}/apache/conf.d/green-web.conf'}
#  notify: # 只要配置文件改动就重启服务一次
#    - restart apache
