---


- name: install airflow webserver service script
  template: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - {'src': 'airflow-web.service' , 'dest':'/etc/systemd/system/airflow-web.service'}

- name: install airflow webserver service script
  template: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - {'src': 'airflow-scheduler.service' , 'dest':'/etc/systemd/system/airflow-scheduler.service'}


- name: start all the service
  systemd: state=started name={{ item }}
  with_items:
    - airflow-webserver
    - airflow-scheduler
